title: Tenfold Path

livereload: true

email: dragan@tenfoldpath.com
url: https://www.tenfoldpath.com
owner: "Dragan Dimitrijevic"
description: "Software Engineer - Freelancer"
cvr: "36128801"

# Color settings (hex-codes without the leading hash-tag)
color:
  primary-dark: '#000000'
  links: '#219ab3'

# Footer settings
footer: Tenfold Path

social:
  - title: web
    icon: globe
    url: https://dragandimitrijevic.com
  - title: facebook
    icon: facebook
    url: http://www.facebook.com/dragan.dimitrijevic.7737

markdown: kramdown

permalink: pretty
