title: Tenfold Path

# livereload: true

email: dragan@tenfoldpath.com
url: https://dragandim.github.io/tenfoldpath.com
owner: "Dragan Dimitrijevic"
description: "Software Engineer - Freelancer"
cvr: "36128801"

# Color settings (hex-codes without the leading hash-tag)
color:
  primary-dark: '#000000'
  links: '#219ab3'

# Footer settings
footer: Tenfold Path

# Social networks usernames (many more available: google-plus, flickr, dribbble, pinterest, instagram, tumblr, linkedin, etc.)
social:
  - title: twitter
    url: https://twitter.com/SBootstrap
  - title: facebook
    url:
  - title: web
    url: https://dragandimitrijevic.com
  - title: github
    url: https://github.com/dragandim

markdown: kramdown

permalink: pretty
